# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
scaler = tf.constant(9)
vector = tf.constant([4, 8, 10])
matrix = tf.constant([[4, 5], [10, 30], [80, 90]])

In [5]:
print('Scaler, Vector, and matrix')
print(scaler, vector, matrix)

Scaler, Vector, and matrix
tf.Tensor(9, shape=(), dtype=int32) tf.Tensor([ 4  8 10], shape=(3,), dtype=int32) tf.Tensor(
[[ 4  5]
 [10 30]
 [80 90]], shape=(3, 2), dtype=int32)


# Broadcasting

In [7]:
result = matrix * scaler
result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 36,  45],
       [ 90, 270],
       [720, 810]], dtype=int32)>

In [10]:
sum_result = matrix + [[2], [9], [2]]
sum_result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  7],
       [19, 39],
       [82, 92]], dtype=int32)>

# Gradient